config/routes.rb
Sitenotifier::Application.routes.draw do
  resources :alerts

  devise_for :users

  get "page/index"

  resources :announcements
  
  match 'dismiss' => 'announcements#dismiss'

  root :to => "page#index"

end

app/models/alert.rb
class Alert < ActiveRecord::Base
  belongs_to :user
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  
  scope :between_now, where("starts_at <= ? AND ends_at >= ?", Time.now, Time.now)
  
  def self.current_announcements(hide_time)

      if hide_time.nil?
        Announcement.between_now.all
      else
        Announcement.where("updated_at > ? OR starts_at > ?", hide_time, hide_time).all
      end

  end
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :alerts
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  # GET /alerts
  # GET /alerts.xml
  def index
    @alerts = Alert.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @alerts }
    end
  end

  # GET /alerts/1
  # GET /alerts/1.xml
  def show
    @alert = Alert.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @alert }
    end
  end

  # GET /alerts/new
  # GET /alerts/new.xml
  def new
    @alert = Alert.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @alert }
    end
  end

  # GET /alerts/1/edit
  def edit
    @alert = Alert.find(params[:id])
  end

  # POST /alerts
  # POST /alerts.xml
  def create
    @alert = Alert.new(params[:alert])

    respond_to do |format|
      if @alert.save
        format.html { redirect_to(@alert, :notice => 'Alert was successfully created.') }
        format.xml  { render :xml => @alert, :status => :created, :location => @alert }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @alert.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /alerts/1
  # PUT /alerts/1.xml
  def update
    @alert = Alert.find(params[:id])

    respond_to do |format|
      if @alert.update_attributes(params[:alert])
        format.html { redirect_to(@alert, :notice => 'Alert was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @alert.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /alerts/1
  # DELETE /alerts/1.xml
  def destroy
    @alert = Alert.find(params[:id])
    @alert.destroy

    respond_to do |format|
      format.html { redirect_to(alerts_url) }
      format.xml  { head :ok }
    end
  end
  
  def dismiss
    # mark as read.
    # AJAX hide alerts
    
  end
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  
  before_filter :authenticate_user!
  
  # GET /announcements
  # GET /announcements.xml
  def index
    @announcements = Announcement.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @announcements }
    end
  end

  # GET /announcements/1
  # GET /announcements/1.xml
  def show
    @announcement = Announcement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @announcement }
    end
  end

  # GET /announcements/new
  # GET /announcements/new.xml
  def new
    @announcement = Announcement.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @announcement }
    end
  end

  # GET /announcements/1/edit
  def edit
    @announcement = Announcement.find(params[:id])
  end

  # POST /announcements
  # POST /announcements.xml
  def create
    @announcement = Announcement.new(params[:announcement])

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to(@announcement, :notice => 'Announcement was successfully created.') }
        format.xml  { render :xml => @announcement, :status => :created, :location => @announcement }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @announcement.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /announcements/1
  # PUT /announcements/1.xml
  def update
    @announcement = Announcement.find(params[:id])

    respond_to do |format|
      if @announcement.update_attributes(params[:announcement])
        format.html { redirect_to(@announcement, :notice => 'Announcement was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @announcement.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.xml
  def destroy
    @announcement = Announcement.find(params[:id])
    @announcement.destroy

    respond_to do |format|
      format.html { redirect_to(announcements_url) }
      format.xml  { head :ok }
    end
  end
  
  def dismiss
    session[:announcement_hide_time] = Time.now
    
    respond_to do |format|
      format.js 
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end

end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_announcements
    @current_announcements ||= Announcement.current_announcements(session[:announcement_hide_time])
  end
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/alerts/_form.html.erb
<%= form_for(@alert) do |f| %>
  <% if @alert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alert.errors.count, "error") %> prohibited this alert from being saved:</h2>

      <ul>
      <% @alert.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :starts_at %><br />
    <%= f.datetime_select :starts_at %>
  </div>
  <div class="field">
    <%= f.label :ends_at %><br />
    <%= f.datetime_select :ends_at %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= select("user", "user_id", User.all.collect {|p| [ p.email, p.id ] }) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alerts/edit.html.erb
<h1>Editing alert</h1>

<%= render 'form' %>

<%= link_to 'Show', @alert %> |
<%= link_to 'Back', alerts_path %>

app/views/alerts/index.html.erb
<h1>Listing alerts</h1>

<table>
  <tr>
    <th>Message</th>
    <th>Starts at</th>
    <th>Ends at</th>
    <th>Read</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @alerts.each do |alert| %>
  <tr>
    <td><%= alert.message %></td>
    <td><%= alert.starts_at %></td>
    <td><%= alert.ends_at %></td>
    <td><%= alert.read %></td>
    <td><%= alert.user_id %></td>
    <td><%= link_to 'Show', alert %></td>
    <td><%= link_to 'Edit', edit_alert_path(alert) %></td>
    <td><%= link_to 'Destroy', alert, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Alert', new_alert_path %>

app/views/alerts/new.html.erb
<h1>New alert</h1>

<%= render 'form' %>

<%= link_to 'Back', alerts_path %>

app/views/alerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Message:</b>
  <%= @alert.message %>
</p>

<p>
  <b>Starts at:</b>
  <%= @alert.starts_at %>
</p>

<p>
  <b>Ends at:</b>
  <%= @alert.ends_at %>
</p>

<p>
  <b>Read:</b>
  <%= @alert.read %>
</p>

<p>
  <b>User:</b>
  <%= @alert.user_id %>
</p>


<%= link_to 'Edit', edit_alert_path(@alert) %> |
<%= link_to 'Back', alerts_path %>

app/views/announcements/_form.html.erb
<%= form_for(@announcement) do |f| %>
  <% if @announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
      <% @announcement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :starts_at %><br />
    <%= f.datetime_select :starts_at %>
  </div>
  <div class="field">
    <%= f.label :ends_at %><br />
    <%= f.datetime_select :ends_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/announcements/dismiss.js.erb
$('#announcement').hide();

app/views/announcements/edit.html.erb
<h1>Editing announcement</h1>

<%= render 'form' %>

<%= link_to 'Show', @announcement %> |
<%= link_to 'Back', announcements_path %>

app/views/announcements/index.html.erb
<h1>Listing announcements</h1>

<table>
  <tr>
    <th>Message</th>
    <th>Starts at</th>
    <th>Ends at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @announcements.each do |announcement| %>
  <tr>
    <td><%= announcement.message %></td>
    <td><%= announcement.starts_at %></td>
    <td><%= announcement.ends_at %></td>
    <td><%= link_to 'Show', announcement %></td>
    <td><%= link_to 'Edit', edit_announcement_path(announcement) %></td>
    <td><%= link_to 'Destroy', announcement, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Announcement', new_announcement_path %>

app/views/announcements/new.html.erb
<h1>New announcement</h1>

<%= render 'form' %>

<%= link_to 'Back', announcements_path %>

app/views/announcements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Message:</b>
  <%= @announcement.message %>
</p>

<p>
  <b>Starts at:</b>
  <%= @announcement.starts_at %>
</p>

<p>
  <b>Ends at:</b>
  <%= @announcement.ends_at %>
</p>


<%= link_to 'Edit', edit_announcement_path(@announcement) %> |
<%= link_to 'Back', announcements_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Site Notifier</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <ul class="hmenu">
    <%= render 'devise/menu/registration_items' %>
    <%= render 'devise/menu/login_items' %>
  </ul>
  
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
  
  <% unless current_announcements.empty? %>
  <div id="announcement">
    <p class="right">x <%= link_to "close", dismiss_path, :remote => true %></p>
    <div>
        <h3>An Important Message:</h3>
        <% for announcement in current_announcements %>
          <p><%=h announcement.message %></p>
        <% end %>
    </div>
  </div>
  <% end %>
  
  <%# add alerts %>
  
  <%= yield %>
  
  <div id="footer">
    <p>This is the Footer</p>
  </div>

</body>
</html>

app/views/page/index.html.erb
<h1>My Fancy Rails App</h1>
<p>And this was the little world in which I had been living securely for years, this fiery chaos!  What had happened in the last seven hours I still did not know; nor did I know, though I was beginning to guess, the relation between these mechanical colossi and the sluggish lumps I had seen disgorged from the cylinder.  With a queer feeling of impersonal interest I turned my desk chair to the window, sat down, and stared at the blackened country, and particularly at the three gigantic black things that were going to and fro in the glare about the sand pits.</p>

<p>They seemed amazingly busy.  I began to ask myself what they could be.  Were they intelligent mechanisms?  Such a thing I felt was impossible.  Or did a Martian sit within each, ruling, directing, using, much as a man's brain sits and rules in his body?  I began to compare the things to human machines, to ask myself for the first time in my life how an ironclad or a steam engine would seem to an intelligent lower animal.</p>

<p>The storm had left the sky clear, and over the smoke of the burning land the little fading pinpoint of Mars was dropping into the west, when a soldier came into my garden.  I heard a slight scraping at the fence, and rousing myself from the lethargy that had fallen upon me, I looked down and saw him dimly, clambering over the palings.  At the sight of another human being my torpor passed, and I leaned out of the window eagerly.</p>

<p>"Hist!" said I, in a whisper.</p>

<p>He stopped astride of the fence in doubt.  Then he came over and across the lawn to the corner of the house.  He bent down and stepped softly.</p>